workflows:
    latera_sales_process:
        steps:
            new_lead:
                label: 'New Lead'
                order: 10
                entity_acl:
                    lead:
                        delete: false
                allowed_transitions:
                    - qualify
                    - disqualify
            disqualified_lead:
                label: 'Disqualified Lead'
                order: 20
                entity_acl:
                    lead:
                        update: false
                        delete: false
                allowed_transitions:
                    - follow_up
                    - reactivate
                is_final: true
            new_opportunity:
                label: 'New Opportunity'
                order: 20
                entity_acl:
                    opportunity:
                        delete: false
                allowed_transitions:
                    - develop
                    - close_as_won
                    - close_as_lost
            first_call:
                label: 'First Call'
                order: 30
                entity_acl:
                    opportunity:
                        delete: false
                allowed_transitions:
                    - interested
                    - close_as_won
                    - close_as_lost
            interested:
                label: 'Interested'
                order: 40
                entity_acl:
                    opportunity:
                        delete: false
                allowed_transitions:
                    - sent_the_offer
                    - close_as_won
                    - close_as_lost
            sent_the_offer:
                label: 'Sent the offer'
                order: 50
                entity_acl:
                    opportunity:
                        delete: false
                allowed_transitions:
                    - preparation_of_the_contract
                    - close_as_won
                    - close_as_lost
            preparation_of_the_contract:
                label: 'Preparation of the contract'
                order: 60
                entity_acl:
                    opportunity:
                        delete: false
                allowed_transitions:
                    - sent_the_invoice
                    - close_as_won
                    - close_as_lost
            sent_the_invoice:
                label: 'Sent the invoice'
                order: 70
                entity_acl:
                    opportunity:
                        delete: false
                allowed_transitions:
                    - close_as_won
                    - close_as_lost
            won_opportunity:
                label: 'Won Opportunity'
                order: 80
                entity_acl:
                    opportunity:
                        update: false
                        delete: false
                allowed_transitions:
                    - reopen
                is_final: true
            lost_opportunity:
                label: 'Lost Opportunity'
                order: 80
                entity_acl:
                    opportunity:
                        update: false
                        delete: false
                allowed_transitions:
                    - reopen
                is_final: true
