imports:
    - { resource: 'hydra_lead/steps.yml' }
    - { resource: 'hydra_lead/attributes.yml' }
    - { resource: 'hydra_lead/transitions.yml' }
    - { resource: 'hydra_lead/transition_definitions.yml' }

workflows:
    hydra_lead:
        label: 'Hydra Sales Lead'
        entity: OroCRM\Bundle\SalesBundle\Entity\Lead
        entity_attribute: lead
        start_step: new
