imports:
    - { resource: 'hydra_opportunity/steps.yml' }
    - { resource: 'hydra_opportunity/attributes.yml' }
    - { resource: 'hydra_opportunity/transitions.yml' }
    - { resource: 'hydra_opportunity/transition_definitions.yml' }

workflows:
    hydra_opportunity:
        label: 'Hydra Sales Opportunity'
        entity: OroCRM\Bundle\SalesBundle\Entity\Opportunity
        entity_attribute: opportunity
        start_step: qualify
        steps_display_ordered: true
