workflows:
    hydra_opportunity:
        steps:
            qualify:
                label: 'Qualify'
                order: 10
                allowed_transitions:
                    - develop
            develop:
                label: 'Develop'
                order: 20
                allowed_transitions:
                    - connect
                    - close_as_won
                    - close_as_lost
            connect:
                label: 'Connect'
                order: 30
                allowed_transitions:
                    - close_as_won
                    - close_as_lost
            close:
                label: 'Closed'
                order: 40
                allowed_transitions:
                    - requalify_lost
                    - requalify_won
                is_final: true
